#UP GESTURE
upXList1 = []
upYList1 = []
upZList1 = []
upXList2 = []
upYList2 = []
upZList2 = []
upXList3 = []
upYList3 = []
upZList3 = []
upXList4 = []
upYList4 = []
upZList4 = []
upXList5 = []
upYList5 = []
upZList5 = []
upXList6 = []
upYList6 = []
upZList6 = []
upXList7 = []
upYList7 = []
upZList7 = []
upXList8 = []
upYList8 = []
upZList8 = []
upXList9 = []
upYList9 = []
upZList9 = []
upXList10 = []
upYList10 = []
upZList10 = []

#DOWN GESTURE
downXList1 = []
downYList1 = []
downZList1 = []
downXList2 = []
downYList2 = []
downZList2 = []
downXList3 = []
downYList3 = []
downZList3 = []
downXList4 = []
downYList4 = []
downZList4 = []
downXList5 = []
downYList5 = []
downZList5 = []
downXList6 = []
downYList6 = []
downZList6 = []
downXList7 = []
downYList7 = []
downZList7 = []
downXList8 = []
downYList8 = []
downZList8 = []
downXList9 = []
downYList9 = []
downZList9 = []
downXList10 = []
downYList10 = []
downZList10 = []

#LEFT GESTURE

#RIGHT GESTURE
