#UP GESTURE
upGesture1 = []
upGesture2 = []
upGesture3 = []
upGesture4 = []
upGesture5 = []
upGesture6 = []
upGesture7 = []
upGesture8 = []
upGesture9 = []
upGesture10 = []

#DOWN GESTURE
downGesture1 = []
downGesture2 = []
downGesture3 = []
downGesture4 = []
downGesture5 = []
downGesture6 = []
downGesture7 = []
downGesture8 = []
downGesture9 = []
downGesture10 = []

#LEFT GESTURE
leftGesture1 = []
leftGesture2 = []
leftGesture3 = []
leftGesture4 = []
leftGesture5 = []
leftGesture6 = []
leftGesture7 = []
leftGesture8 = []
leftGesture9 = []
leftGesture10 = []

#RIGHT GESTURE
rightGesture1 = []
rightGesture2 = []
rightGesture3 = []
rightGesture4 = []
rightGesture5 = []
rightGesture6 = []
rightGesture7 = []
rightGesture8 = []
rightGesture9 = []
rightGesture10 = []